import "./globals.css";
import type { Metadata } from "next";
import { Indie_Flower, Roboto } from "next/font/google";

const indieFlower = Indie_Flower({
  weight: "400",
  subsets: ["latin"],
  variable: "--indie-flower",
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${indieFlower.variable}`}>
        <div className="layout">{children}</div>
      </body>
    </html>
  );
}
